### ISSUE TITLE
SciPy 2016 Proceedings MDAnalysis paper

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/scipy_proceedings#1]
As part of the Scipy 2016 presentation we also want to submit a short overview over MDAnalysis to be included in the conference proceedings:

> Full papers are also encouraged to accompany all invited talks and posters.  These will be reviewed for inclusion in the proceedings. Instructions for submitting a full paper can be found here: https://github.com/scipy-conference/scipy_proceedings. Drafts will be due May 30th, at which point reviews will begin. We expect you will be then working synchronously with your reviewers. 
- Deadline for drafts: **May 30, 2016**
- All authors on the abstract are also authors on the paper, i.e. team @MDAnalysis/scipy2016 
- _This repository_ is a fork of _scipy_proceedings repo_ and we will use the **2016 branch** (the default) it to write the paper. Submission of the paper is done as a PR against the scipy_proceedings repo's 2016 branch.
- The wiki has some [basic instructions for contributing](/MDAnalysis/scipy_proceedings/wiki).

(This issue takes over from MDAnalysis/scipy-2016#2.)

**Comment by orbeckst** [comment]
@MDAnalysis/scipy2016  : Deadline for the scipy proceedings draft is TOMORROW (Monday May 30, 2016).

> Submissions must be received by May 30th at 23:59 PST, but modifications are allowed during the open review period which ends July 5th at 18:00 PST. Submissions are considered received once a Pull Request has been opened following the procedure outlines below.

I am working on this today (Sunday) and Monday. 
- **I will submit the PR against the scipy_proceedings repo close to 23:59 PST (~23:30 PST).**
- **After 20:00 PST I will merge whatever is pending** and apply best judgment if it does not merge perfectly. _Please make sure that you have all your stuff merged by 20:00 PST or have PRs that are mergeable._ 
- If you can  **provide other information but not complete PRs** (see, for instance, issues #18, #19, #20) then please **have this in by 10:00 PST** so that I have a chance integrating it into the text.

Note: x (PST) = x (AZ) = x + 8 (London) = x + 9 (Paris) (and I assume that they actually mean PDT)

**Comment by orbeckst** [comment]
ping @MDAnalysis/scipy2016 : please check this issue for notes on the scipy proceedings papers (deadline May 30, 2016, 23:59 PDT).

**Comment by dotsdl** [comment]
Looks good! PR!

**Comment by orbeckst** [comment]
submitted PR scipy-conference/scipy_proceedings#212

Thanks everyone.
