### ISSUE TITLE
One line per independent clause.

### ISSUE THREAD

**Issue by dotsdl** [MDAnalysis/scipy_proceedings#10]
First broached in #6.

Can we do one line per sentence/independent clause? That makes diffs more meaningful, and gets those of us that use a text editor that relies on hard breaks for basic navigation (e.g. vim) what we need to **not** lose our minds. :D

**Comment by kain88-de** [comment]
@dotsdl currently there is one line per independent clause (aka paragraph). I just changed that in the last commit of #6. In my other PR's I kept the one line per paragraph.

**Comment by dotsdl** [comment]
A paragraph is not an independent clause. In most cases each sentence is an independent clause, but it could also mean two clauses separated by a ";". Basically, I'm proposing that each "independent" statement be separated with a newline.

**Comment by orbeckst** [comment]
I am happy to try and follow this guideline (even though this is not what I normally do... normally I just have emacs do hard line breaks after 79 cols...). In emacs I will use 

```
fill-column 99999
visual-line-mode
```

and try to remember to hit return after each sentence.

But please don't start screaming if not everything follows these rules perfectly...

**Comment by dotsdl** [comment]
Just changed my settings in vim to make navigation through soft-wrapped text easier. You can always navigate with `gj` and `gk` to go down/up through flowed text, but to make this more natural one can do:

``` vim
autocmd FileType rst nnoremap <expr> j v:count ? 'j' : 'gj'
autocmd FileType rst nnoremap <expr> k v:count ? 'k' : 'gk'
```

This will make `j` and `k` do flowed text, too. My personal gripe is much smaller now, but I think it's still smart to make diffing/merging easier by keeping it one sentence per line as proposed. I'd hate to read a whole paragraph to play "spot the change" when reviewing a PR (or worse, merging entire paragraphs, possibly losing something along the way).
