### ISSUE TITLE
acknowledgements

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/scipy_proceedings#16]
@MDAnalysis/scipy2016  – please add acknowledgements to the draft (e.g. any grants that you get paid on). Double-check with your PI if necessary. It is often very important that all grant numbers are listed because this is one way in which successes of grants are measured. 

(We can fix this in review but it's good to be complete from the start.)
# Authors Acknowledgement TODO:
- [x] @richardjgowers 
- [x] @kain88-de
- [x] @jbarnoud 
- [x] @tylerjereddy 
- [x] @mnmelo 
- [x] @sseyler
- [x] @jandom 
- [x] @dotsdl 
- [x] @seb-buch 
- [x] @ianmkenney 
- [x] @orbeckst

**Comment by orbeckst** [comment]
ping @MDAnalysis/scipy2016 – please provide me with your language for the acknowledgements section

**Comment by richardjgowers** [comment]
With these do we want to split it by authors (RG was supported by xyz) or just list all numbers together (This work was in part supported by abc, xyz, etc(

**Comment by jandom** [comment]
Wait, what does this mean? Should we give like our PhD grant number that
we're supported by?
- Jan

**Comment by orbeckst** [comment]
The personalized version of @richardjgowers is clearer than what I started with, so use

```
OB was supported in part by grant XYZ from the National Science Foundation.
```

**Comment by orbeckst** [comment]
@jandom : typically, yes but check with your PI. If unsure about the exact number, just say something along the lines of

  JD was supported by the Wellcome Trust.

(or whatever and we fill in the gaps later.)

**Comment by kain88-de** [comment]
I edited the first post to track who already supplied information.

**Comment by orbeckst** [comment]
Good idea, thanks!

> On 29 May, 2016, at 09:41, kain88-de notifications@github.com wrote:
> 
> I edited the first post to track who already supplied information.

## 

Oliver Beckstein \* orbeckst@gmx.net
skype: orbeckst  \* orbeckst@gmail.com

**Comment by orbeckst** [comment]
Add acknowledgements in author order.

**Comment by orbeckst** [comment]
@seb-buch emailed me, he read it, and is happy with everything.

**Comment by orbeckst** [comment]
Groningen folks: @jbarnoud and @mnmelo – anything to add to acknowledgements?

If you have any other text snippets or figures that you'd like to see included, please open an issue quickly. PRs are most convenient but I can also work with text and attached figures...

**Comment by jbarnoud** [comment]
I asked my PI for what I need to add to the acknowledgements. It will most likely not get the answer before the submission deadline, though. 
Le 30 mai 2016 9:17 PM, Oliver Beckstein notifications@github.com a écrit :Groningen folks: @jbarnoud and @mnmelo – anything to add to acknowledgements?

If you have any other text snippets or figures that you'd like to see included, please open an issue quickly. PRs are most convenient but I can also work with text and attached figures...

**Comment by orbeckst** [comment]
We can add it later.

> On 30 May, 2016, at 12:39, Jonathan Barnoud notifications@github.com wrote:
> 
> I asked my PI for what I need to add to the acknowledgements. It will most likely not get the answer before the submission deadline, though. 

## 

Oliver Beckstein \* orbeckst@gmx.net
skype: orbeckst  \* orbeckst@gmail.com

**Comment by kain88-de** [comment]
Only @mnmelo is missing now.

**Comment by mnmelo** [comment]
I've just updated the draft. Should this be closed now?

**Comment by orbeckst** [comment]
Yes, I think you we're the last one. Please close. 

## 

Oliver Beckstein
email: orbeckst@gmail.com

Am Jun 2, 2016 um 8:39 schrieb mnmelo notifications@github.com:
