### ISSUE TITLE
visualization example

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/scipy_proceedings#19]
@tylerjereddy can you provide me with an example for streamlines
- [ ] image (as produced by the MDA code)
- [ ] scientific background
- [ ] python code
- [ ] any citations

You can point me to the docs or provide me with something new. The more detail the better.

**Comment by tylerjereddy** [comment]
This may come down to the wire but at least I'm in the Pacific time zone at the moment so maybe the 20:00 PST (if not earlier) could be doable. I'd probably just use the docs example though, but I'll see if I can write something in.

**Comment by orbeckst** [comment]
Ok, thanks. I'll wait or something from you. 

## 

Oliver Beckstein
email: orbeckst@gmail.com

Am May 30, 2016 um 5:05 schrieb Tyler Reddy notifications@github.com:
