### ISSUE TITLE
paragraph on trajectory offsets for random access

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/scipy_proceedings#31]
Could I please get a paragraph outlining our approach to speeding up trajectory access?

This is pretty unique in the way that we do it. @mnmelo ?

**Comment by richardjgowers** [comment]
Also worth mentioning we do this for ascii files too which allows us to
seek them too

**Comment by kain88-de** [comment]
That should go into basic usage right.

@orbeckst I'd appreciate if we do this days before the deadline next time and not hours!

**Comment by kain88-de** [comment]
the basic usage already hints at it but doesn't mentiong that it's super awesome that we actually do that.

**Comment by orbeckst** [comment]
> On 30 May, 2016, at 12:22, kain88-de notifications@github.com wrote:
> 
> @orbeckst I’d appreciate if we do this days before the deadline next time and not hours!

I hear you.

If there are things that you can’t do today: that’s fine, just say in the issue. It’s not a problem. I know that this is all late. Pretty much everything is a “nice to have”. I can always put a stub in the draft. It’s generally just better if someone wrote something who actually did the work.

The conference paper is really not such a big deal. If it’s not perfect then that won’t be the end of the world. As long as it looks fairly reasonable (and it already does) we’ll have an opportunity to fix-up until July 5.

**Comment by kain88-de** [comment]
I would like to add this when we have a PR to unify the offset store and load behavior. Currently we only support it for XDR files (the PDB file generates them at every load). After that we can go into detail how this is solved in a _general_ way in MDAnalysis

**Comment by orbeckst** [comment]
Good point @kain88-de . Then I'd just want to say that stored offsets (which originated in LOOS) are a viable solution to providing random access for any trajectory format. We have already implemented it for the Gromacs formats and will soon be adding this to all formats.

The full MDA paper will then have a more in-depth discussion of stored offsets and benchmarks.

**Comment by kain88-de** [comment]
Yes you can say that. I'd appreciate it if you could add that because I'm not sure where it would fit best.

**Comment by orbeckst** [comment]
Ok, will do. Just add comments here (goes for @mnmelo , too).
