### ISSUE TITLE
draft amendments

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/scipy_proceedings#34]
@MDAnalysis/scipy2016 : The draft was submitted (PR scipy-conference/scipy_proceedings#212) but we can still amend the paper (and I have already done this extensively). You may continue submitting PRs inside _this_ repository against the 2016 branch. Please have a quick look and if you want to change anything, please submit a PR or leave a note here.

If you just want to say "all ok" please do that – good to have explicit agreement, too.

To keep things orderly, I'll do the merges — just assign each PR to @orbeckst.

In order to keep the submission clean, I removed all unnecessary files. However, I am keeping the [with-PDF branch](https://github.com/MDAnalysis/scipy_proceedings/tree/with-PDF) around. As described on the wiki under [Makefile on branch with-PDF](https://github.com/MDAnalysis/scipy_proceedings/wiki#makefile-on-branch-with-pdf), this branch is periodically rebased against 2016 and the PDF  [MDAnalysis_SciPy_2016.pdf](https://github.com/MDAnalysis/scipy_proceedings/blob/with-PDF/papers/oliver_beckstein/MDAnalysis_SciPy_2016.pdf) is committed:

```
git checkout with-PDF
git rebase 2016
make
git add MDAnalysis_SciPy_2016.pdf
git commit --amend -C HEAD   # the top commit is "rebuilt PDF"
git push -f origin with-PDF
```

Thus, you should always be able to browse the latest PDF of the draft at  [MDAnalysis_SciPy_2016.pdf](https://github.com/MDAnalysis/scipy_proceedings/blob/with-PDF/papers/oliver_beckstein/MDAnalysis_SciPy_2016.pdf).

**Comment by seb-buch** [comment]
All OK for me.
The paper underlines very well the "swiss army knife on steroids" aspect of MDAnalysis and presents all the recent performance enhancements.
I take my hat off to all the contributors!

![thumb up](http://static4.fjcdn.com/thumbnails/comments/Since+when+is+everyone+playing+fallout+3+again+_54d72d2f823ebd5f2caa44c1df00d45d.png)

**Comment by mnmelo** [comment]
Awesome work, everyone!

I've found higher resolution versions of the netCDF and NumPy logos, and I think they'll make Fig 1 cleaner. (The biopython logo also needs minor position adjustments). PR soon.
I'm also not sure that the hierarchy is well depicted in Fig 1. Should we discuss this in a separate issue? (Does it matter?)

**Comment by orbeckst** [comment]
PR & suggestions welcome!

> On 2 Jun, 2016, at 10:09, mnmelo notifications@github.com wrote:
> 
> Awesome work, everyone!
> 
> I've found higher resolution versions of the netCDF and NumPy logos, and I think they'll make Fig 1 cleaner. (The biopython logo also needs minor position adjustments). PR soon.
> I'm also not sure that the hierarchy is well depicted in Fig 1. Should we discuss this in a separate issue? (Does it matter?)
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

Oliver Beckstein \* orbeckst@gmx.net
skype: orbeckst  \* orbeckst@gmail.com

**Comment by kain88-de** [comment]
@orbeckst how is the review process going?

**Comment by orbeckst** [comment]
> On 5 Jul, 2016, at 00:08, Max Linke notifications@github.com wrote:
> 
> @orbeckst how is the review process going?

I think I addressed all questions by the reviewer. They were all good comments and fairly easy to address. You can follow the discussion at https://github.com/scipy-conference/scipy_proceedings/pull/212

If you have any last minute changes or fixes please get them in soon.

**Comment by orbeckst** [comment]
The reviewer at  scipy-conference/scipy_proceedings#212 recommended the manuscript for merging. We're done. Thanks everyone!

You can get the PDF as [MDAnalysis_SciPy_2016.pdf](https://github.com/MDAnalysis/scipy_proceedings/blob/with-PDF/papers/oliver_beckstein/MDAnalysis_SciPy_2016.pdf).
