### ISSUE TITLE
mdakit paper: check author information

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/scipy_proceedings#37]
The initial deadline for the SciPy MDAKit paper is **this Friday** June 2. I used the Whitepaper with some minor changes as a basis.

The current **author list** is modeled after the Whitepaper: alphabetical and @IAlibay is corresponding author. I consider it open for discussion, though: @IAlibay and @lilyminium have done a lot of the work (registry, cookiecutter, original whitepaper), with @ianmkenney recently moving the project forward. We can have a discussion in the comments below or on discord/email/zoom — it does not have to be solved by Friday because we can still change the authors during review.

Please confirm that you agree to be an author on the paper, that your name is spelled correctly, and that the correct affiliation and email is listed by either checking the box below or leaving a comment. Also check the Acknowledgements for relevant funding information and make any updates in the reST file `papers/ian_kenney/ian_kenney.rst`.

- [x] @IAlibay 
- [x] @jbarnoud 
- [x] @orbeckst 
- [x] @richardjgowers 
- [x] @ianmkenney 
- [x] @fiona-naughton 
- [x] @lilyminium

**Comment by IAlibay** [comment]
Looks like everyone has agreed authorship, closing as completed.
