### ISSUE TITLE
create PR for submission

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/scipy_proceedings#38]
Create a PR against the 2023 scipy_proceedings branch as described in https://github.com/scipy-conference/scipy_proceedings#create-a-paper-pr in order to submit the manuscript **by Friday June 2**.

Make sure that the author list is complete #37 .

**Comment by IAlibay** [comment]
@ianmkenney @orbeckst - is this completed? I see a draft PR, but it's unclear to me if it needs to be out of draft stage to count as done.

**Comment by orbeckst** [comment]
Thanks for the reminder. Ian took it out of draft.

We can continue working on it.

**Comment by orbeckst** [comment]
Submitted PR is https://github.com/scipy-conference/scipy_proceedings/pull/816
