### ISSUE TITLE
change style to indicate results instead of intentions

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/scipy_proceedings#41]
The current style is not appropriate for a paper that reports results. Instead it contains many phrases that express plans or future work — which was appropriate for a whitepaper. But we now have implementations and a number of packages so we have to change to reporting results instead of intentions.

**Comment by orbeckst** [comment]
Basically, delete any "would", "could", "will endeavor" etc... simple present tense rules.

**Comment by orbeckst** [comment]
Did PR #42 fix this?

**Comment by lilyminium** [comment]
Fixed by #42.
