### ISSUE TITLE
cite python software

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/scipy_proceedings#5]
packages like pandas and numpy matplotlib and the like actually all have some proceedings paper that they would like to cite when working with the software. We should cite them here as well because it also stand in the author guidelines. I'll check again what papers that are

**Comment by kain88-de** [comment]
There exists a handy [overview page](https://scipy.org/citing.html)

**Comment by orbeckst** [comment]
Excellent, thanks @kain88-de !
